# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/oliverzheng/private-cocoapods.git'

target 'fourplay' do
  pod 'VDKQueue', '~> 0.1.0'
end

target 'fourplayTests' do

end

